--- #YAML:1.0
name:                Sort-Key
version:             1.28
abstract:            the fastest way to sort anything in Perl
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Test::More:                    0.54
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Salvador Fandino <sfandino@yahoo.com>
